Repository entando-k8s/entando-k8s-operator-bundle, pull requests merged in 2021-04, with the labels that each got.

#8 ENDOC-311 update individual CRD descriptions
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
  manifests/entandoapps.entando.org.crd.yaml
  manifests/entandoclusterinfrastructures.entando.org.crd.yaml
  manifests/entandocompositeapps.entando.org.crd.yaml
  manifests/entandodatabaseservices.entando.org.crd.yaml
  manifests/entandodebundles.entando.org.crd.yaml
  manifests/entandokeycloakservers.entando.org.crd.yaml
  manifests/entandoplugins.entando.org.crd.yaml
Labels: size/L

#9 ENG-2114 propagated pvc changes
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
Labels: approved, size/S

#10 bumped openssl for latest cve fixes
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
Labels: size/L

#11 Combined packaging of operator deployment permutations
  Chart.yaml
  Dockerfile.internal
  Dockerfile.rh-cert
  README.md
  build-index.sh
  generate-deployments.sh
  jenkins-x.yml
  local-dev-publish.sh
  manifests/entando-k8s-operator-configmap.yaml
  manifests/k8s-116-and-later/cluster-resources/entando-editor-clusterrole.yaml
  manifests/k8s-116-and-later/cluster-resources/entandoapppluginlinks.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandoapps.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandoclusterinfrastructures.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandocompositeapps.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandodatabaseservices.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandodebundles.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandokeycloakservers.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/entandoplugins.entando.org.crd.yaml
  manifests/k8s-116-and-later/cluster-resources/pod-viewer-clusterrole.yaml
  manifests/k8s-116-and-later/cluster-scoped-deployment/all-in-one.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/all-in-one.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/cluster-resources.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/namespace-resources.yaml
  manifests/k8s-116-and-later/olm-deployment/docker-image-info-configmap.yaml
  manifests/k8s-116-and-later/olm-deployment/entando-empty-tls-secret.yaml
  manifests/k8s-116-and-later/olm-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  manifests/k8s-116-and-later/rh-cert-deployment/docker-image-info-configmap.yaml
  manifests/k8s-116-and-later/rh-cert-deployment/entando-empty-tls-secret.yaml
  manifests/k8s-116-and-later/rh-cert-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  manifests/k8s-before-116/cluster-resources/entando-editor-clusterrole.yaml
  manifests/k8s-before-116/cluster-resources/entandoapppluginlinks.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandoapps.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandoclusterinfrastructures.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandocompositeapps.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandodatabaseservices.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandodebundles.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandokeycloakservers.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/entandoplugins.entando.org.crd.yaml
  manifests/k8s-before-116/cluster-resources/pod-viewer-clusterrole.yaml
  manifests/k8s-before-116/cluster-scoped-deployment/all-in-one.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/all-in-one.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/cluster-resources.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/namespace-resources.yaml
  requirements.yaml
  set-csv-version.sh
  skaffold.yaml
  templates/docker-image-info-configmap.yaml
  templates/entando-empty-tls-secret.yaml
  templates/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  test.json
  values.yaml
Labels: approved, size/XXL

#13 V6.3.2 pr4
  Dockerfile.internal
  Dockerfile.rh-cert
  build-index.sh
  generate-deployments.sh
  local-dev-publish.sh
  manifests/k8s-116-and-later/cluster-scoped-deployment/all-in-one.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/all-in-one.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/namespace-resources.yaml
  manifests/k8s-116-and-later/olm-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  manifests/k8s-116-and-later/rh-cert-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  manifests/k8s-before-116/cluster-scoped-deployment/all-in-one.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/all-in-one.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/namespace-resources.yaml
  metadata/annotations.yaml
  publish-for-certification.sh
  requirements.yaml
  templates/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  values.yaml
Labels: size/XL

#14 Eng 2294 fixed cm embedded failure
  manifests/k8s-116-and-later/cluster-scoped-deployment/all-in-one.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/all-in-one.yaml
  manifests/k8s-116-and-later/namespace-scoped-deployment/namespace-resources.yaml
  manifests/k8s-116-and-later/olm-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  manifests/k8s-116-and-later/rh-cert-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml
  manifests/k8s-before-116/cluster-scoped-deployment/all-in-one.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/all-in-one.yaml
  manifests/k8s-before-116/namespace-scoped-deployment/namespace-resources.yaml
  values.yaml
Labels: size/L
