Repository entando-k8s/entando-k8s-operator-bundle, pull requests merged in 2021-03, with the labels that each got.

#2 Initial jenkins-x import
  jenkins-x.yml
  manifests/entando-empty-tls-secret.yaml
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
  skaffold.yaml
  tests/scorecard/placeholder.txt
Labels: approved, size/M

#4 ENG-2068 using latest ubi images
  jenkins-x.yml
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
  set-csv-version.sh
Labels: approved, size/M

#3 Update entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
Labels: ok-to-test, size/M

#5 Update entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
Labels: approved, size/XS

#7 ENG-2099 fixed CRDs and patched entando-k8s-database-service-controller
  manifests/entando-k8s-operator.v0.3.x.clusterserviceversion.yaml
  manifests/entandoapps.entando.org.crd.yaml
  manifests/entandodatabaseservices.entando.org.crd.yaml
  manifests/entandokeycloakservers.entando.org.crd.yaml
  manifests/entandoplugins.entando.org.crd.yaml
Labels: approved, size/S
